proxy_cache_path /var/cache/nginx/journey keys_zone=journey:10m max_size=100m inactive=60s;

upstream django {
    server web1:8000;
    server web2:8000;
}

server {
    listen 80;

    location / {
        proxy_pass http://django;
        proxy_set_header Host $host;

        proxy_cache journey;
        proxy_cache_valid 200 10s;
        proxy_cache_bypass $cookie_sessionid;
        proxy_no_cache $cookie_sessionid;

        add_header X-Cache $upstream_cache_status always;
        add_header X-Served-By $upstream_addr always;
    }

    location /me {
        proxy_pass http://django;
        proxy_set_header Host $host;
        add_header X-Cache BYPASS always;
        add_header X-Served-By $upstream_addr always;
    }


}